const regionOptions = [
    { value: '1', label: 'Mombasa' },
    { value: '2', label: 'Kwale' },
    { value: '3', label: 'Kilifi' },
    { value: '4', label: 'Tana River' },
    { value: '5', label: 'Lamu' },
    { value: '6', label: 'Taita Taveta' },
    { value: '7', label: 'Garissa' },
    { value: '8', label: 'Wajir' },
    { value: '9', label: 'Mandera' },
    { value: '10', label: 'Marsabit' },
    { value: '11', label: 'Isiolo' },
    { value: '12', label: 'Meru' },
    { value: '13', label: 'Tharaka-Nithi' },
    { value: '14', label: 'Embu' },
    { value: '15', label: 'Kitui' },
    { value: '16', label: 'Machakos' },
    { value: '17', label: 'Makueni' },
    { value: '18', label: 'Nyandarua' },
    { value: '19', label: 'Nyeri' },
    { value: '20', label: 'Kirinyaga' },
    { value: '21', label: 'Murang\'a' },
    { value: '22', label: 'Kiambu' },
    { value: '23', label: 'Turkana' },
    { value: '24', label: 'West Pokot' },
    { value: '25', label: 'Samburu' },
    { value: '26', label: 'Trans Nzoia' },
    { value: '27', label: 'Uasin Gishu' },
    { value: '28', label: 'Elgeyo-Marakwet' },
    { value: '29', label: 'Nandi' },
    { value: '30', label: 'Baringo' },
    { value: '31', label: 'Laikipia' },
    { value: '32', label: 'Nakuru' },
    { value: '33', label: 'Narok' },
    { value: '34', label: 'Kajiado' },
    { value: '35', label: 'Kericho' },
    { value: '36', label: 'Bomet' },
    { value: '37', label: 'Kakamega' },
    { value: '38', label: 'Vihiga' },
    { value: '39', label: 'Bungoma' },
    { value: '40', label: 'Busia' },
    { value: '41', label: 'Siaya' },
    { value: '42', label: 'Kisumu' },
    { value: '43', label: 'Homa Bay' },
    { value: '44', label: 'Migori' },
    { value: '45', label: 'Kisii' },
    { value: '46', label: 'Nyamira' },
    { value: '47', label: 'Nairobi' },
  ];

  export default regionOptions;